import { List, ListItem, Link, Flex, Img } from '@chakra-ui/react';

import logo from './assets/logo.svg';

export const Nav = () => (
  <nav>
    <Flex
      maxWidth="1920px"
      m="auto"
    >
      <List
        display="flex"
        justifyContent="space-between"
        width="100%"
        m="37px 70px"
        sx={{ '& li': { display: 'inline' } }}
      >
        <ListItem>
          <Link
            variant="navLink"
            href="#"
          >
            About
          </Link>
        </ListItem>
        <ListItem>
          <Link
            variant="navLink"
            href="#"
          >
            Tickets
          </Link>
        </ListItem>
        <ListItem>
          <Link
            variant="navLink"
            href="#"
          >
            Speakers
          </Link>
        </ListItem>
        <ListItem>
          <Link
            variant="navLink"
            href="#"
          >
            Agenda
          </Link>
        </ListItem>
        <ListItem>
          <Img
            mt="-10px"
            src={logo}
          />
        </ListItem>
        <ListItem>
          <Link
            variant="navLink"
            href="#callSponsors"
          >
            Sponsors
          </Link>
        </ListItem>
        <ListItem>
          <Link
            variant="navLink"
            href="#callCommunities"
          >
            Communities
          </Link>
        </ListItem>
        <ListItem>
          <Link
            variant="navLink"
            href="#"
          >
            Contacts
          </Link>
        </ListItem>
      </List>
    </Flex>
  </nav>
);
